### ISSUE TITLE
parsing relion 3.1 star file doesn't work

### ISSUE THREAD

**Issue by azazellochg** [zhonge/cryodrgn#10]
Hi, I'm trying to run the first step to downsample particles using a relion 3.1 star file:
```
00020:   source ~/rc/conda.rc&& conda activate cryodrgn-0.2.1 && cryodrgn downsample Runs/000416_CryoDrgnProtPreprocess/extra/input_particles.star  -o Runs/000416_CryoDrgnProtPreprocess/extra/downsampled_parts.mrcs  --datadir Runs/000130_ProtRelionPreprocessParticles/extra -D 64 
00021:   Traceback (most recent call last):
00022:     File "/home/azazello/soft/scipion3/scipion_home/software/em/void/cryodrgn/cryodrgn/dataset.py", line 25, in load_particles
00023:       particles = starfile.Starfile.load(mrcs_txt_star, relion31=relion31).get_particles(datadir=datadir, lazy=lazy)
00024:     File "/home/azazello/soft/scipion3/scipion_home/software/em/void/cryodrgn/cryodrgn/starfile.py", line 60, in load
00025:       assert words.ndim == 2, f"Uneven # columns detected in parsing {set([len(x) for x in words])}. Is this a RELION 3.1 starfile?" 
00026:   AssertionError: Uneven # columns detected in parsing {0, 1, 3, 9, 11}. Is this a RELION 3.1 starfile?
```
Are 3.1 files not supported yet (I'm using latest master branch)?

**Comment by azazellochg** [comment]
I have found the relion31 flag for parse_pose_star and parse_ctf_star. I see that it doesn't exist for downsample. Also, looking at the parser, I'd suggest to parse "data_particles" table for 3.1. This is how it's always called. In old relion versions it can be data_ or data_Particles.

**Comment by zhonge** [comment]
Thanks! I forgot to add the --relion31 flag to downsample. Fixed in top of tree. I also updated the parsing to look for the data_particles block. Thank you for your input --  I wasn't sure what the spec was before.

**Comment by azazellochg** [comment]
Thank you! One more thing, if the optics table is after particles table, https://github.com/zhonge/cryodrgn/blob/master/cryodrgn/starfile.py#L44 will fail. Maybe read until the first empty line?

**Comment by azazellochg** [comment]
actually, there are more issues. Particles table in 3.1 does not have any acquisition metadata (voltage, sph aberration etc) - they have moved to optics table, so you would have to read it as well.

**Comment by zhonge** [comment]
Good catch! Thank you -- I only had a few examples of RELION 3.1 star files to go on.

Updated in commit feac9f69a795ae3fc56dd966c3b15917ea20e50c.

I haven't implemented parsing of the data_optics block, so the CTF parameters have to be input manually (assuming that all particles have the same kv/w/cs/ps arguments). 

Added some asserts that these parameters are provided in commit ba8aa67f4cd86477af403d1176442da6801d3b18

**Comment by azazellochg** [comment]
Brilliant, thanks a lot for quick fixes, @zhonge ! One more tiny thing: ps (phase shift) is in the particles table, so no need to set it separately (also it will be different for different mics).

**Comment by zhonge** [comment]
Took out the assert for --ps in commit 81657fd2d821ab3ab65cd274a280a95dbf9493c8. I forgot about that -- thanks! The argument was originally there to handle star files that don't have the _rlnPhaseShift column. Let me know if you run into or notice anything else!

**Comment by lkater** [comment]
Hi, 
I know this issue is closed but it would be super helpful if you would mention the --relion31 flag in the doc or in the help. It took me a while to recreate a relion3.0 star file until I found the flag by chance.
Thanks for the great work
