### ISSUE TITLE
Will DRGN2 provide a nvidia-docker build?

### ISSUE THREAD

**Issue by changephilip** [zhonge/cryodrgn#100]
Installing DRGN following the installation guide always met variant kinds of errors for me.😭
I found a  DRGN docker builded by [slaclab/cryodrgnand](https://hub.docker.com/r/slaclab/cryodrgn/tags) it works well with my video card.
A docker build image will make it easy to utilize?🥺

**Comment by zhonge** [comment]
Hi, thanks for reporting. I will keep this in mind for the future, and can ask the maintainer at SLAC who is hosting the docker builds to get the latest versions.
