### ISSUE TITLE
Parsing poses from cryoSPARC Non-Uniform Refinement 

### ISSUE THREAD

**Issue by ts387** [zhonge/cryodrgn#102]
I was wondering if it is fine to parse poses from a cryoSPARC non-uniform (consensus) refinement, as opposed to regular homogeneous refinement. The poses are likely to be more accurate, but is there a reason one shouldn't?

**Comment by zhonge** [comment]
Yes, it is fine to use poses from a non-uniform refinement, and definitely preferred if the poses are more accurate!

**Comment by ts387** [comment]
Thank you!
