### ISSUE TITLE
analyze_convergence.py Syntax Error

### ISSUE THREAD

**Issue by dushyantj** [zhonge/cryodrgn#103]
Hi,

I am trying to use analyze_convergence.py script however, I am getting the following error:

File "utils/analyze_convergence.py", line 838
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
                  ^
SyntaxError: invalid syntax

Can you please help me troubleshoot this since I am not a python expert?

Thank you very much.

Dushyant

**Comment by ts387** [comment]
I also get this error.
