### ISSUE TITLE
Graph traversal - plotting indices back on UMAP plot

### ISSUE THREAD

**Issue by ktoropova** [zhonge/cryodrgn#106]
Hi Ellen, 

Thank you for the documentation on graph traversal, it's been very helpful :) 

I'd like to be able to see where the sampled structures are positioned in e.g the UMAP plot - so I have the list of indices in the path.txt file but I'm not sure now how to plot this back on to the UMAP plot (and how to find out which k cluster the indices belong to). Can this be done in the Jupyter notebook? 

Related to this, I've seen in your talks that you have a very cool plot of the 'walk' taken during the graph traversal that you play next to the extracted structures. If possible could you share how you do this? 

Thanks very much in advance!
Kat

**Comment by Guillawme** [comment]
Hi Kat,

I posted a recipe here: https://github.com/zhonge/cryodrgn/discussions/79
I don't know if this is exactly how Ellen made her movies, but this is what worked for me.

I hope this helps! (if not, maybe post in #79 so we follow up there and have everything in one place).

**Comment by ktoropova** [comment]
Thank you Guillaume! Apologies for the duplication. I'll give it a go!
Best wishes,
Kat

**Comment by ktoropova** [comment]
Hi Guillaume,
Just wanted to follow up with a thanks so much for recipe, it worked
beautifully!
All the best,
Kat



Katerina Toropova, PhD
Institute of Structural and Molecular Biology
Birkbeck, University of London, WC1E 7HX
***@***.***
***@***.***
