### ISSUE TITLE
Convert write_starfile.py script to cryodrgn command

### ISSUE THREAD

**Issue by zhonge** [zhonge/cryodrgn#110]
The `write_starfile.py` script seems to be used a lot to convert selections of particles in cryodrgn back to `.star` files for refinement in other tools. 

TODO: Make this a cryodrgn command instead of a script in the utils subdirectory.

**Comment by Zyqiii1** [comment]
Hi, dear Zhong! I was very glad to know this update. In the website: https://github.com/zhonge/cryodrgn/commit/2bd9a64e8a0caa84e677622cac021b41cba30483, I revised everywhere according to the document. However, I used the command: '**cryodrgn write_starfile -h**' or '**cd testing/ && bash test_utils.sh**'. The Error information is: 
**cryodrgn: error: invalid choice: 'write_starfile' (choose from 'downsample'...........)**
I did not know what happened. Can you help me?

**Comment by zhonge** [comment]
It depends on your current installation setup, but you're probably missing the reinstall step:

```
# get latest source code
$ cd /path/to/source/code
$ git pull origin master

# re-run installation
$ python setup.py install
```

See here for more: https://www.notion.so/cryoDRGN-installation-with-anaconda-4cff0367d9b241bb8d902efe339d01e6#3e0eed7f61214c55902ad8752716abf4
