### ISSUE TITLE
Particle ordering does not match

### ISSUE THREAD

**Issue by jgruber310** [zhonge/cryodrgn#114]
Hi,
I am trying to use write_starfile.py to create a .star file for RELION to continue refinement at full scale. However, when I use the --keep-micrograph flag and the --ref-star flag, I receive the following error message:

assert len(ref_star) == len(particles), f"Particle ordering in {args.particles} must match {args.ref_star}"
AssertionError: Particle ordering in particles.128.txt must match all_relion_particles.star

The code I am using is:

particles.128.txt ctf.pkl --poses poses.pkl --ind trial/02_vae128/ind_keep.66410_particles.pkl --datadir /path/to
/parent/relion/MotionCorr/job003/data/Data --full-path --ref-star all_relion_particles.star --keep-micrograph -o GMM_class3_v2.star

particles.128.txt is the text file referencing the chunks of downscaled particles
all_relion_particles.star is the .star file generated from the .mrcs of the same name exported from relion during the initial step

Do you have suggestions as to how I can keep the micrograph information for further RELION processing or how to fix the disagreement in particle ordering?

Thanks,
- Josie

**Comment by zhonge** [comment]
Thanks Josie. Your command looks fine to me so far. A quick followup -- do you know what version of cryodrgn you are using? 
```
cryodrgn --version
```

**Comment by jgruber310** [comment]
We are running cryodrgn 0.3.4 on a linux cluster

**Comment by zhonge** [comment]
I think I might see the problem. The `--datadir` flag is being used for the input particles, not the reference starfile. Although, this might be an unrelated issue since the particle paths aren't needed for the reference star since we're just getting the micrograph coordinates... 

I'm going to push an update to the script that gives a more helpful error message. In the meantime, could you try the following in a python session (to check the number of particles):

```
from cryodrgn import dataset, starfile
particles = dataset.load_particles('particles.128.txt', lazy=True)
ref_star = starfile.Starfile.load('all_relion_particles.star')
print(len(particles))
print(len(ref_star))
```

**Comment by zhonge** [comment]
By the way, there's a utils script `filter_star.py` that you can use to filter the original `all_relion_particles.star` file by the cryodrgn index.pkl (assuming that there isn't a problem in your input star file). 

https://github.com/zhonge/cryodrgn/blob/master/utils/filter_star.py

```
python filter_star.py all_relion_particles.star --ind trial/02_vae128/ind_keep.66410_particles.pkl -o all_relion_particles_filtered.star
```

This should only be used if the input relion star file describes the same particle stack that was used to train cryodrgn. The images can be downsampled but the particle stack should otherwise be the same (e.g. same total number of particles and same ordering).

**Comment by jgruber310** [comment]
Here are my results, following your suggestion
print(len(particles))
959561
print(len(ref_star))
1

Does this indicate a problem with the initial star file? That seems odd because I used that initial star file for all of my cryodrgn processing and when I open the star file, I do have 959561 entries. When I use the filter_star.py I get the following error

raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Int64Index([    15,     55,     56,    161,    201,    215,    268,    269,\n               272,    284,\n            ...\n            959508, 959530, 959543, 959544, 959545, 959550, 959555, 959556,\n            959557, 959559],\n           dtype='int64', length=66410)] are in the [index]"

**Comment by zhonge** [comment]
Could you send me the star file via email (zhonge@mit.edu)? I can look into what's going on.

**Comment by jgruber310** [comment]
After some tinkering, I was able to export particles and continue processing them in Relion by using a modified version of write_starfile.py and the starparser package. It is likely the changes I made to the python file were rendered unnecessary by the cryoDRGN 1.0 update, but I will describe my whole process for anyone else who is using cryoDRGN 0.3.4 and having the same issue. In all my previous steps for cryoDRGN I used the --relion31 flag. I finished processing my particles in Relion 3.1. You can find starparser here:
https://github.com/sami-chaaban/starparser 

1. We edited the if args.ref_star section of the write_starfile.py to accept the --relion31 flag. The section now looks like this:

```
if args.ref_star:
        ref_star = starfile.Starfile.load(args.ref_star, relion31=True)
        print("Debug:", len(ref_star), len(particles))
        assert len(ref_star) == len(particles), f"Particle ordering in {args.particles} must match {args.ref_star}"
```

2. We executed the new write_starfile.py, including the full path and the option to pull from the original Relion data

```
path/to/write_starfile.py particles.128.txt ctf.pkl --poses poses.pkl 
         --ind path/to/selected/ind_keep.5000_particles.pkl 
         --datadir /path/to/orig/relion/MotionCorr/job003/data/Data 
         --full-path 
         --ref-star cryodrgn_input_particles.star #this is the original particle file used to start your cryoDRGN workflow
         --keep-micrograph 
         -o selected_particles_relion30.star
```

3. We converted this starfile from Relion3.0 (output of write_starfile.py) to Relion3.1 using relion_convert_star. This command does not actually add all the necessary attributes to the optics group and the star file will not work in Relion3.1 if you continue straight from this point. We rectify this by further modifying the optics group using starparser in subsequent steps, so using relion_convert_star may be totally unnecessary and you could probably just skip straight to the starparser conversion to get a Relion3.1 star file.

```
relion_convert_star --i selected_particles_relion30.star --o selected_particles_relion31.star 
       --Cs 2.7       #enter the spherical aberration for your microscope
       --Q0 0.1      #enter the phase amplitude used in your Relion pipeline
```

4. Next we re-extracted the same particles used for the initial cryoDRGN input at the same box size used in the final cryoDRGN step using Relion3.1. In our case, we used a 128 box size. This will generate a star file that has exactly the same optics group information that you want your cryoDRGN output to have (spherical aberration, phase amplitude, pixel size, dimensions, box size, etc.)
5. Using the starparser package available on GitHub, we then swapped the optics group from the Relion output in step 4 with the optics group of the star file generated in step 3. This will result in a star file suitable for using all your cryoDRGN selected particles in Relion3.1

```
starparser --i selected_particles_relion31.star 
          --swap_optics 
          --f 128box_particles_.star      #this is the star file generated by Relion3.1 in step 4 when you re-extract at the same box size used in cryoDRGN
          --o particles_final.star
```

6. In the Relion3.1 GUI, you can then use particles_final.star as the input file for an Import job using the 'Other Node Type' option and importing them as 'particles STAR file (.star)'. The result of this job can be used to re-extract at full-scale and works just as any other particle star file.
