### ISSUE TITLE
pose.{EPOCH}.pkl output

### ISSUE THREAD

**Issue by jianhaoc** [zhonge/cryodrgn#121]
**Describe the bug**
In cryoDRGN_viz.ipynb, I see "pose.{EPOCH}.pkl".
# Load poses
if config['dataset_args']['do_pose_sgd']:
    pose_pkl = f'{WORKDIR}/pose.{EPOCH}.pkl'
But, in my output of "cryodrgn train_vae" according to the manual, there is no pose.*.pkl files generated.

**To Reproduce**
What is the command you used?

cryodrgn train_vae -o cdtrain0001_box128_z8 --zdim 8 --poses pose.pkl --ctf ctf.pkl -n 25 -v --amp --multigpu ptcl_cryodrgn-box128.mrcs

**Expected behavior**
How to generate pose.*.pkl output?

**Additional context**

**Comment by zhonge** [comment]
Hi, I think you may have accidentally modified the cell if there is an issue in getting the notebook to run. The pose.pkl is one of the _inputs_ to cryodrgn that you provide `--poses /path/to/parsed/input/pose.pkl`. 

If you use the (experimental!) flag `--do-pose-sgd` during training, there will be updated poses in the output directory.
