### ISSUE TITLE
No GPUs detected + solution

### ISSUE THREAD

**Issue by mcahn** [zhonge/cryodrgn#125]
I had a problem where, if I ran ```quicktest.sh```, cryoDRGN would report:
```
2022-07-29 17:21:57     Use cuda False
2022-07-29 17:21:57     WARNING: No GPUs detected
```
None of the fixes I found online worked, so I wanted to share my solution.  I don't believe this has anything to do with cryoDRGN, instead it's pytorch that has the problem.  I ran the installation on the head node of a cluster. While the head node has cudatoolkit installed, it does not actually have a GPU.  (The compute nodes have GPU's).  I'm not sure if that was the reason pytorch decided there were no GPU's, even when run on a compute node.

To fix this I uninstalled pytorch and friends:
```
conda uninstall pytorch torchvision torchaudio 
```
and then instead of pytorch I installed pytorch-gpu.  (This seems to install both a small pytorch-gpu package, and a larger pytorch package).
```
conda install pytorch-gpu torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
```
RHEL 8.5
CryoDRGN 1.1.0
Python 3.9.13
Cudatoolkit 11.6

Perhaps this will be useful to someone.

Matthew Cahn

**Comment by zhonge** [comment]
Thank you Matthew!
