### ISSUE TITLE
Error during installation (unrecognized arguments: --no-build)

### ISSUE THREAD

**Issue by ts387** [zhonge/cryodrgn#126]
**Describe the bug**
An error is received during jupyter labextension install as part of wider CryoDRGN v1.1 installation (like below).

```
(cryodrgn1.1_local) [ts387@login1 ~]$ jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
usage: jupyter-lab [-h] [--debug] [--show-config] [--show-config-json] [--generate-config] [-y] [--allow-root]
                   [--no-browser] [--autoreload] [--script] [--no-script] [--core-mode] [--dev-mode] [--splice-source]
                   [--expose-app-in-browser] [--extensions-in-dev-mode] [--collaborative]
                   [--log-level ServerApp.log_level] [--config ServerApp.config_file] [--ip ServerApp.ip]
                   [--port ServerApp.port] [--port-retries ServerApp.port_retries] [--sock ServerApp.sock]
                   [--sock-mode ServerApp.sock_mode] [--transport KernelManager.transport]
                   [--keyfile ServerApp.keyfile] [--certfile ServerApp.certfile] [--client-ca ServerApp.client_ca]
                   [--notebook-dir ServerApp.root_dir] [--preferred-dir ServerApp.preferred_dir]
                   [--browser ServerApp.browser] [--pylab ServerApp.pylab] [--gateway-url GatewayClient.url]
                   [--watch [LabApp.watch]] [--app-dir LabApp.app_dir]
                   [extra_args ...]
jupyter-lab: error: unrecognized arguments: --no-build
```

**To Reproduce**
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build

**Expected behavior**
Expected to recognise --no-build argument.

**Additional context**
Didn't happen before during installation of previous versions.

**Comment by Guillawme** [comment]
I initially came up with these revised installation instructions (see 0abd779d5b3a4add90e944bda0b4aac980c53b9e and c5a8014f87fd5e8fe509407b2d353c0f0453f6c0), and I noticed that it was overall a bit faster to use this `--no-build` flag for each jupyter plugin installation and then do a single `build` at the end.

But it should work fine if you simply omit this `--no-build` flag from the installation commands. You will simply have to wait a bit longer for each of these commands to complete, as each one will build the corresponding plugin.

I hope this helps.

**Comment by zhonge** [comment]
Feel free to reopen if you are still running into issues.

**Comment by Guillawme** [comment]
@ts387 I just did a fresh installation of the latest cryoDRGN in a fresh conda environment, following the instructions from the README, and I did _not_ get this `jupyter-lab: error: unrecognized arguments: --no-build`.

I suspect this depends on the version of jupyterlab used. The versions of the relevant pieces in my conda environment are:

```
jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39hf3d152e_0    conda-forge
jupyter_server            1.18.1           py39h06a4308_0  
jupyterlab                3.4.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
```

You can check these versions in your conda environment with the following command (assuming your environment is active; if not, activate it first):

```
conda list | grep jupyter
```

Unless specifying versions explicitly, conda should always install whichever is the newest at the time you run the `conda install ...` commands. So it is possible (even likely) that we don't have the exact same versions, but it would be surprising if they differed a lot (like several major version numbers of difference), and this kind of difference in interface (presence or absence of a command-line option) generally doesn't happen in minor version number changes.

**Comment by ts387** [comment]
Thanks @Guillawme.

So looks like it DID install a different version of the jupyter client for me:

```
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39hf3d152e_0    conda-forge
jupyter_server            1.18.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.4              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.15.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
```

So should I simply omit the `--no-build` flag in each case, or replace it with `build`? In the latter case, do I then skip the last command in the series (`jupyter lab build`)?

Could you please write out explicitly what different series of commands I might run instead of the ones in the README?

Thanks again 🙂👍

**Comment by Guillawme** [comment]
Hi @ts387 

Omit all the `--no-build` at the end of the commands that have them, and also omit the final `jupyter lab build`. Each command will take a little longer to complete, but the installation should work fine otherwise.

**Comment by ts387** [comment]
Dear @Guillawme @zhonge 

I tried this but it leads to the following:

`(cryodrgn1.1_local) bash-4.4$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
[C 2022-08-25 08:55:31.520 ServerApp] No such file or directory: /home/ts387/labextension`

It now seems to be confusing "labextension", any ideas?

**Comment by ts387** [comment]
@Guillawme @zhonge 

I think this is being caused by a conflicting alias defined in my ~/.bashrc. I will repeat and check, and post again if it doesn't solve the issue.

Many thanks for your help.
