### ISSUE TITLE
Tutorial downsample command chunk option unrecognized

### ISSUE THREAD

**Issue by tomgoddard** [zhonge/cryodrgn#133]
In the cryodrgn tutorial the example downsampling command fails with cryodrgn 1.1.0 when copied and pasted to a shell using Safari on Mac.

(cryodrgn) $ cryodrgn downsample L17Combine_weight_local.mrcs -D 256 -o particles.256.mrcs —-chunk 50000
cryodrgn: error: unrecognized arguments: —-chunk 50000

It took a few minutes to figure out this puzzle.  The problem is the dashes in the "--chunk" are not a normal dash character -- apparently some UTF-8 dash look-alike.  It might help others to fix the tutorial so a normal dash character is used.

**Comment by tomgoddard** [comment]
This is the tutorial

https://www.notion.so/cryoDRGN-EMPIAR-10076-tutorial-c8728dcc88e744c8827447c3ff094d19

**Comment by zhonge** [comment]
Thanks so much for bringing this up! That is indeed extremely subtle (especially when viewed on the Notion page). I fixed it just now. 

Unrelated, but @vineetbansal reported another typo in the tutorial referring to `cryodrgn write_starfile` which has now been renamed `cryodrgn_utils write_star`. 

Vineet @vineetbansal is a research software engineer at Princeton who just started helping me with cryodrgn development/support moving forward.

**Comment by tomgoddard** [comment]
Thanks!
