### ISSUE TITLE
ipywidgets>=8.0 and pythreejs>=2.4 appear to error during analysis notebook interactive plot

### ISSUE THREAD

**Issue by bpowell122** [zhonge/cryodrgn#137]
**Describe the bug**
Running the `cryodrgn_filtering_template.ipynb` cell `widget, fig, ind_table = analysis.ipy_plot_interactive(df); VBox((widget,fig,ind_table))` causes an error message and prevents rendering of the interactive plot. This appears to be due to specific ipywidgets (and potentially pythreejs) versions. It may be useful to temporarily add `"ipywidgets<8.0"  "pythreejs<2.4.0"` constraints to the cryoDRGN installation instructions. 

**To Reproduce**
My conda environment contains the following relevant versions:
`ipywidgets                8.0.2              pyhd8ed1ab_1    conda-forge`
`pythreejs                 2.4.1              pyhc268e32_0    conda-forge`
Running the `cryodrgn_filtering_template.ipynb` notebook through the `analysis.ipy_plot_interactive(df)` cell causes (1) the x/y/color_by/colormap widget to load, (2) two identical error messages to appear, and (3) the figure and ind_table to not be rendered.

**Expected behavior**
Normally this command produces a plot to render and be interactively configurable for x axis / y axis / color_by column / colormap, and reports mouse-lasso-selected indices in a table below.

**Additional context**
Running the command `conda install "pythreejs<2.4.0" "ipywidgets<8.0" -c conda-forge`, re-launching the notebook, and re-running the cell in question causes the expected behavior to occur. The conda command caused the following environment changes:
`ipywidgets         conda-forge::ipywidgets-8.0.2-pyhd8ed~ --> pkgs/main::ipywidgets-7.6.5-pyhd3eb1b0_1`
`pythreejs          conda-forge/noarch::pythreejs-2.4.1-p~ --> conda-forge/linux-64::pythreejs-2.1.0-py37_0`
`widgetsnbextension conda-forge/noarch::widgetsnbextensio~ --> pkgs/main/linux-64::widgetsnbextension-3.5.2-py37h06a4308_0`
I've only tested this in jupyter notebook, not jupyter lab. This bug might be related to this one [here](https://github.com/plotly/plotly.py/issues/3686). I'm attaching screenshots of the error message below rather than copying the error because the error message itself was rendered differently from typical python tracebacks in my experience and I'm not sure if others may find that useful. 
![screencap1](https://user-images.githubusercontent.com/81090946/188934916-9f1a0b07-ef3b-45a9-999d-064dccfdc61a.png)
![screencap2](https://user-images.githubusercontent.com/81090946/188934917-c64c8ed0-19b8-440b-a55e-3f3ffbc2225b.png)
![screencap3](https://user-images.githubusercontent.com/81090946/188934918-2bd8cc96-fa7f-409d-88f0-5969a45c4ae0.png)

**Comment by zhonge** [comment]
@vineetbansal can you take a look at this?

**Comment by vineetbansal** [comment]
Hello @bpowell122 - thanks for your investigations. Most helpful. I'm able to confirm that a new installation of `cryoDRGN` without being specific about `ipywidgets` version does cause issues with the interactive filtering cell (I see just the dropdown widgets but not the actual rendered interactive graph).

It seems to me that in the [link](https://github.com/plotly/plotly.py/issues/3686) that you have provided, the issues lies with `ipywidgets 8` (and above). I tried specifying `ipywidgets<8` in our `setup.py` and I see that things start working again, and I can filter the particles using the Lasso tool. So I'm inclined to pin `ipywidgets` as you suggest. I'm not seeing `pythreejs` installed in my environment at all. `cryoDRGN` certainly doesn't need that dependency directly, and it looks like nothing it depends on needs it either. I'm not sure how you ended up with it.

Let me know if the above fix would be acceptable, and I can incorporate it in today.

**Comment by bpowell122** [comment]
Thanks for checking and refining the bug+fix! Pinning ipywidgets<8 sounds like the appropriate solution here. pythreejs likely snuck in on my end as a dependency from ipyvolume for some other visualizations I'm trying out with cryodrgn, so not including that package sounds like the correct decision.

**Comment by zhonge** [comment]
Thanks for digging into this! Please re-open if there are any more issues.
