### ISSUE TITLE
Jupyterlab interactive widget plot does not show

### ISSUE THREAD

**Issue by janekjlee** [zhonge/cryodrgn#153]
I followed the steps  #34 to install jupyter-lab. I tried opening jupyter-notebook and jupyter-lab on difference devices, and re-ran cryodrgn analyze and the issue is the same every time. For interactive plots, I can see the table to choose axis/color but I see no plot display, even after waiting 30+ minutes. The rest of the plots in jupyter-lab display normally, only the interactive plots do not display. How can I solve this issue? Thanks!

![jupyter-lab](https://user-images.githubusercontent.com/115122535/194185790-403932c6-831f-4457-87ac-af0d384caf32.PNG)

**Comment by vineetbansal** [comment]
Hi @janekjlee - can you try installing `pip install ipywidgets<8` (or the corresponding `condo install`, though we've only tested out the former).

It seems there is a pending issue with `ipywidgets` 8 and greater (https://github.com/plotly/plotly.py/issues/3686) that they're still working on.

If things work, then the graph should be rendered almost immediately and you shouldn't have to wait.

**Comment by janekjlee** [comment]
Hi, thank you for your response! In a clean environment, I installed ipywidgets==7.7 and everything else normally from the README page. Now when I use jupyter-lab, everything else works, but I get this error for interactive widget.
![image](https://user-images.githubusercontent.com/115122535/194452887-1733908a-50e3-4123-b851-6aa36c7584b8.png)

**Comment by vineetbansal** [comment]
Hi @janekjlee - the instructions on the `README` are for dependency installation might be a bit dated and are currently under review. What we've found works in our case is the current list of dependencies in `pyproject.toml`:

```
    "torch>=1.0.0",
    "pandas",
    "numpy",
    "matplotlib",
    "scipy>=1.3.1",
    "scikit-learn",
    "seaborn",
    "cufflinks",
    "jupyterlab",
    "umap-learn",
    "ipywidgets<8"
```

Perhaps you want to try to (in a clean conda environment), do a `pip install -e .` which will install all the above requirements, and see if things work for you?

**Comment by janekjlee** [comment]
Thank you for your help! I got the interactive widgets to work.
