### ISSUE TITLE
Possibly bogus warning about image size not being multiple of 8

### ISSUE THREAD

**Issue by olibclarke** [zhonge/cryodrgn#167]
Hi,

When running `train_vae` on input data that has been downsampled to 128px, I see the following warning in the logfile:

`2022-10-25 09:04:37.639848     Warning: Masked input image dimension is not a mutiple of 8 -- AMP training speedup is not optimized`

Is this warning incorrect (and therefore can be ignored), or is there some alteration to image size or scaling happening during preprocessing?

The input command was:

`cryodrgn train_vae ank_downsample_128.mrcs --ind ank_downsample_200k.pkl --ctf ank_ctf.pkl --poses ank_pose_fixed.pkl -n 50 -o ./train_vae_test_200k/ --multigpu -n 50 --zdim 8 >> train_vae_test_200k.log`

Using version: `cryoDRGN 1.0.1.dev126+g04c4a90`

**Comment by zhonge** [comment]
The warning can be ignored. It is just saying that the training time might be slower if the (masked) image dimension isn't a multiple of 8. This will make a bigger difference for larger images, but the training time difference is usually negligible for `D=128` images.
