### ISSUE TITLE
keyword argument 'cuda' in analyze_convergence.py

### ISSUE THREAD

**Issue by frozenfas** [zhonge/cryodrgn#181]
**Describe the bug**
When running analyze_convergence.py with cryoDRGN 1.1.2.dev111+gdb61f72 (master branch, I think). I get the following error.

`line 761, in generate_volumes
    analysis.gen_volumes(
TypeError: gen_volumes() got an unexpected keyword argument 'cuda'`

I think the correct keyword should be device (as given in analysis.py), so in line 761, if you switch cuda=cuda to device=cuda it seems to run as expected. Is this a correct fix?

**Comment by vineetbansal** [comment]
Hi @frozenfas - thanks. You're right. The `cuda` flag in the `analysis` module was recently replace by `device`. I thought I'd got all the references fixed, but I missed this one. This should be fixed shortly.

I don't think there's any documentation pages for the `analyze_convergence` script, but if you're aware of any other place besides the `analyze_convergence.py` script that needs tweaking, let us know.
