### ISSUE TITLE
Inquiry of beta

### ISSUE THREAD

**Issue by kimdn** [zhonge/cryodrgn#19]
In https://github.com/zhonge/cryodrgn

can I interpret

--beta BETA           Choice of beta schedule or a constant for KLD weight
                        (default: 1.0)

as the one in beta-vae (https://openreview.net/forum?id=Sy2fzU9gl)?

If so, then using cryodrgn's train_vae with --beta 2 means that essentially I'm using cryodrgn in beta-vae.

**Comment by zhonge** [comment]
Correct, beta is the weight in front of the KL divergence term in the loss function. I recommend keeping this at the default value, but you're welcome to experiment.
