### ISSUE TITLE
It seems that there are something wrong with your email zhonge@mit.edu

### ISSUE THREAD

**Issue by Icecream-blue-sky** [zhonge/cryodrgn#25]
I have used both gmail and my education mailbox to send a email to you. But it seems that you didn't receive it at all. Is there anything wrong with you email? May be your mailbox is full. Please check it, thanks!

**Comment by zhonge** [comment]
I either missed it or it went to spam -- go ahead and resend.

**Comment by Icecream-blue-sky** [comment]
I

> I either missed it or it went to spam -- go ahead and resend.

I have resended the email. My edu email is tqzouustc@mail.ustc.edu.cn. Please check it.Thanks

**Comment by Icecream-blue-sky** [comment]
> I either missed it or it went to spam -- go ahead and resend.

I have resended the email. My edu email is tqzouustc@mail.ustc.edu.cn. Please check it.Thanks
