### ISSUE TITLE
Wrong version reported for v0.3.0b

### ISSUE THREAD

**Issue by mcianfrocco** [zhonge/cryodrgn#26]
Hi @zhonge - just putting this on your radar that when cryodrgn version is queried it returns the previous version number even though I'm running v0.3.0b: 

```
$ cryodrgn --version
cryoDRGN 0.2.1b
```

Mike

**Comment by apayne97** [comment]
Same, after:

```
$ git pull
$ python setup.py install
$ cryodrgn --version
cryoDRGN 0.2.1b
```

**Comment by zhonge** [comment]
Thank you for pointing this out! Fixed in top-of-tree. Issue was that the version number was written in two places -- Should be fixed now for future versions.
