### ISSUE TITLE
Cannot downsample .mrcs file from EMPIAR-10049

### ISSUE THREAD

**Issue by cgymem17** [zhonge/cryodrgn#266]
**Describe the bug**
When I want to downsample `ragSEC_150309.mrcs`(box size is 192) from dataset EMPIAR-10049 and use the command
 `cryodrgn downsample ragSEC_150309.mrcs -D 128 -o particles_150309.128.mrcs`, it just stopped with this output

<img width="624" alt="截屏2023-04-09 上午10 05 07" src="https://user-images.githubusercontent.com/80606153/230777394-a6124ebe-180c-4516-8f4b-1218e5cd7275.png">

**Comment by zhkim216** [comment]
I got the same error and I fixed it by increasing cpu numbers and memories. But Idk why this fixed the issue :(

**Comment by zhonge** [comment]
Hopefully you were able to get everything else to run correctly. Please reopen if there are any other issues, thanks!
