### ISSUE TITLE
Re-extracting filtered particles

### ISSUE THREAD

**Issue by Jason-vR** [zhonge/cryodrgn#285]
Hi Ellen,

Is there an updated description of how to re-extract particles at higher resolution after filtering?

The 'Re-extracting particles from the micrograph' section of the empiar_tutorial lists the same command as the 'converting to a .star file'.

I'm interested in moving back into Relion after selecting clusters so trying to find a way to write out unbinned star files. I started the workflow by importing a run_data.star and chunking the 2.7M particles for input into cryodrgn train.

Thanks,
Jason

**Comment by zhonge** [comment]
Hi Jason, thank you for asking, and sorry about the slow response. We've been working on cleaning up the documentation and moving it over to gitbook, now available here: 
https://ez-lab.gitbook.io/cryodrgn/cryodrgn-empiar-10076-tutorial#converting-to-a-.star-file

We recently updated how `cryodrgn_utils write_star` preserves the original .star file's metadata.  Before, there was an explicit flag to copy over micrograph coordinates (linking to the old documentation [here](https://www.notion.so/cryodrgn/cryoDRGN-EMPIAR-10076-tutorial-c8728dcc88e744c8827447c3ff094d19?pvs=4#7ba225f4d6df4926858e46d6d8dce5b3) for completeness). The current recommended workflow is to instead filter the original .star file with `cryodrgn_utils filter_star`:

```
cryodrgn_utils filter_star [input reference.star] --ind /path/to/subset/indices.pkl -o filtered.star
```

Alternatively, `cryodrgn write_star` can also perform this filtering if you give the reference star file as an input:

```
cryodrgn_utils write_star [input reference.star] --ind /path/to/subset/indices.pkl --ctf /path/to/ctf.pkl --poses /path/to/poses.pkl -o filtered.star
```

We're planning on putting together a guide on how to import/export particles, but let us know if this works or if you have any questions in the meantime.

**Comment by Jason-vR** [comment]
Thanks Ellen,

That worked perfectly!
