### ISSUE TITLE
Are the input images already aligned?

### ISSUE THREAD

**Issue by LivC93** [zhonge/cryodrgn#294]
Hi thank you very much for making the code available, and apologies if this question has been asked before, or if I missed it in the methods section

Are the images already aligned? (i.e. rotation variance is not an issue)
Also are you taking the ϕ angles from standard software like RELION or CryoSPARK?

**Comment by Guillawme** [comment]
Hello,

For `cryodrgn train_vae`, you need to provide Euler angles along with the particle images. So in this sense yes, the particle images are "already aligned". The angles come from a 3D refinement done in RELION or cryoSPARC. The commands `cryodrgn parse_pose_star` and `cryodrgn parse_pose_csparc` read these angles from a star or cs file, respectively, and write them into a format cryoDRGN can read. The `--do-pose-sgd` option to `cryodrgn train_vae` makes it try to further refine these Euler angles.

For `cryodrgn abinit_het`, you don't need to supply Euler angles: this procedure includes pose search. It takes longer to run, of course, but in my experience it can sometimes replace 2D and 3D classification and find rare states that did not manifest at all in 2D class averages.
