### ISSUE TITLE
which pixel value for analyze?

### ISSUE THREAD

**Issue by kimdn** [zhonge/cryodrgn#30]
According to https://github.com/zhonge/cryodrgn

I need to specify original dimension when I generate pose.pkl

This pose.pkl is used for train_vae that uses my downsampled mrcs

Then, when I run
`cryodrgn analyze`
should I enter original pixel size (1.33 A) since pose.pkl used the original dimension?
or should I enter adjusted pixel size (5.32 A = 1.33 x 256/64) since my train_vae used downsampled mrc?

Thanks.

**Comment by zhonge** [comment]
Thanks for the question. Use the pixel size of the images that are used in training -- e.g. if you trained on 64x64 images, the reconstructed volume would be 64^3, and the pixel size should set to that of the downsample images (5.32A). 

The pixel size used in the earlier pre-processing step of `parse_pose_star`/`parse_pose_csparc` is to make sure that the units from the consensus refinement are correctly converted.
