### ISSUE TITLE
Details of the EMPIAR-10076 homogeneous reconstruction

### ISSUE THREAD

**Issue by RuyiLian** [zhonge/cryodrgn#31]
Hi,

Thanks for sharing your nice work 👍 I am trying to reproduce the experiments of your ICLR paper. In appendix C, it says that poses were determined by aligning the images to **a mature LSU structure obtained from a homogeneous reconstruction of the full resolution dataset in cryoSPARC**, i.e. "a consensus reconstruction". 

Could you please provide more details on how to get the reconstruction from the particle images of EMPIAR-10076? Thanks!

**Comment by zhonge** [comment]
The consensus reconstruction is provided in this repository: 
https://github.com/zhonge/cryodrgn_empiar

The consensus reconstruction was performed in cryoSPARC v2.4 on the full resolution images from EMPIAR-10076 with the ab-initio job followed by the homogeneous refinement job using all default settings. The final poses are here: 
https://github.com/zhonge/cryodrgn_empiar/blob/main/empiar10076/inputs/poses.pkl
