### ISSUE TITLE
Bug in cryoDRGN_filtering.ipynb  RR.from_dcm depreciated in Scipy 1.4 and above

### ISSUE THREAD

**Issue by DHouldershaw** [zhonge/cryodrgn#39]
Hi,
Minor bug in cryoDRGN_filtering_template.ipynb when using latest scipy (v1.6.1), I get the error:
AttributeError                            Traceback (most recent call last)
<ipython-input-62-3b6e7682e3ee> in <module>
      1 # Convert rotation matrices to euler angles
----> 2 euler = RR.from_dcm(rot).as_euler('zyz', degrees=True)

AttributeError: type object 'scipy.spatial.transform.rotation.Rotation' has no attribute 'from_dcm'

From the release notes to Scipy v1.4.0 (https://docs.scipy.org/doc/scipy/reference/release.1.4.0.html))  scipy deprecations 
"In scipy.spatial.Rotation methods from_dcm, as_dcm were renamed to from_matrix, as_matrix respectively. The old names will be removed in SciPy 1.6.0."

Replacing 'from_dcm'  with 'from_matrix' makes the error go away :)
Many Thanks, Cheers, Dave H.

**Comment by rubyfroom** [comment]
This issue also arises in write_starfile.py when providing the optional `--poses` input (leaving it out, it runs file with a single .mrcs file). I tried modifying write_starfile.py but couldn't find any specific instance of `from_dcm` to replace with `from_matrix`.

My input:
```python $SRC/utils/write_starfile.py particles.128.mrcs ctf.pkl --poses poses.pkl --ind training/ind_keep.147047_particles.pkl -o output.star
```

Output:
```
2021-03-18 13:46:47     147047 particles
2021-03-18 13:46:47     Filtering to 147047 particles
Traceback (most recent call last):
  File "/home/darst/cryodrgn/utils/write_starfile.py", line 91, in <module>
    main(parse_args().parse_args())
  File "/home/darst/cryodrgn/utils/write_starfile.py", line 72, in main
    eulers = utils.R_to_relion_scipy(poses[0]) 
  File "/home/darst/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2b0-py3.7.egg/cryodrgn/utils.py", line 128, in R_to_relion_scipy
    euler = RR.from_dcm(rot*f).as_euler('zxz', degrees=True)
AttributeError: type object 'scipy.spatial.transform.rotation.Rotation' has no attribute 'from_dcm'
```

Thanks!!

**Comment by zhonge** [comment]
Updated for the function call used in write_starfile.py (commit 05108339401dcfef31ea93d8fa403504dcaa6316). Thanks!

Just missed including this in the v0.3.2 release... but fixed in top of tree!
