### ISSUE TITLE
Parallelization of downsampling

### ISSUE THREAD

**Issue by Guillawme** [zhonge/cryodrgn#42]
Hello,

This is low priority, especially if it's complicated to implement. But it would be nice if `cryodrgn downsample` was optionally parallelized, so it could run faster on multi-core computers (the one I use has 80 cores and downsampling was only using one core; not a big deal for small datasets, but it took a very long time for ~0.4 M particles).

A related question: the way I have worked so far was to extract particles at their original (finest) pixel size in RELION, then put them all in the same file with `relion_stack_create`, then downsample this stack with `cryodrgn downsample` to whatever box size I need for a given run. Does it make a difference if I downsample during the RELION Extract job? (could be faster in certain cases, since it is parallelized with MPI, although the extraction step adds to the run time so not sure it would be faster overall).

**Comment by zhonge** [comment]
Yes, the downsampling step is written in a very naive way right now, and there are some speedups I've been meaning to add even without parallelization.

You can definitely downsample during the relion extract job! Will likely be many times faster. Thanks for the question.

**Comment by zhonge** [comment]
Downsampling is now parallelized across threads (`--max-threads 16` by default) in both `cryodrgn downsample` and `cryodrgn preprocess`. Let me know if there are any issues!

**Comment by Guillawme** [comment]
Great, I will give it a try next time I use cryoDRGN! Feel free to close this issue for now, I will know where to find it and reopen if I encounter bugs.
