### ISSUE TITLE
Import error in write_starfile.py

### ISSUE THREAD

**Issue by rubyfroom** [zhonge/cryodrgn#47]
Hi Ellen, I pulled the latest code. Getting an import error now when trying to run `write_starfile.py` (even though cryodrgn environment is active). Would appreciate any guidance- thanks!!:

```Traceback (most recent call last):
  File "/home/darst/cryodrgn/utils/write_starfile.py", line 12, in <module>
    from cryodrgn import dataset
ImportError: No module named cryodrgn

**Comment by zhonge** [comment]
Were you able to get this to work? I bet there was something weird that happened with the anaconda environment, and would recommend de-activating and re-activating the environment:
```
$ conda deactivate
$ conda activate cryodrgn # replace with the name that you used
```
Otherwise, can you provide the commands you used to update the version?
