### ISSUE TITLE
NameError: name 'amp' is not defined

### ISSUE THREAD

**Issue by donghuachensu** [zhonge/cryodrgn#54]
Hi Ellen, I am using cryodrgn version 0.3.3b0. It could not recognize the option 'amp'. Here is the error:

Traceback (most recent call last):
  File "/sdf/home/d/donghuac/anaconda3/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.3b0', 'console_scripts', 'cryodrgn')())
  File "/sdf/home/d/donghuac/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.3b0-py
3.7.egg/cryodrgn/__main__.py", line 52, in main
    args.func(args)
  File "/sdf/home/d/donghuac/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.3b0-py
3.7.egg/cryodrgn/commands/train_vae.py", line 379, in main
    model, optim = amp.initialize(model, optim, opt_level='O1')
NameError: name 'amp' is not defined

**Comment by zhonge** [comment]
You'll need to download Nvidia's apex library in your conda environment to use `--amp` for accelerated training. 

https://github.com/NVIDIA/apex#quick-start

Note that this only works for GPUs that have tensor cores (e.g. Nvidia Volta, Turing, and Ampere architectures, V100s, A100s, RTX2080, etc), which is why it's not in the general installation instructions.

**Comment by donghuachensu** [comment]
Hi, Ellen:

I installed apex after 'conda activate cryodrgn' as the following (note that apex is a separate folder out of cryodrgn)

git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

However, I still got the same error:
 File "/sdf/home/d/donghuac/anaconda3/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.
7.egg/cryodrgn/commands/train_vae.py", line 377, in main
    model, optim = amp.initialize(model, optim, opt_level='O1')
NameError: name 'amp' is not defined


Any suggestions about apex installation? Thanks a lot!

**Comment by zhonge** [comment]
I saw that you got amp running on another thread so closing this issue.

Can you update with how you installed apex?

**Comment by zhonge** [comment]
Was apex successfully installed? If it was then the import should have worked. Can you provide the log for installing apex?

**Comment by donghuachensu** [comment]
I am not very familiar with SBgrid. I guess all related programs including cryodrgn were installed by SBgrid consortium (https://sbgrid.org/software/tag/em).

**Comment by donghuachensu** [comment]
Ellen, I am still not able to install --amp correctly for cryodrgn. Any suggestion?
