### ISSUE TITLE
CryoDRGN FILTERING & viz.ipynb

### ISSUE THREAD

**Issue by EB-kim** [zhonge/cryodrgn#56]
When I set dim =2, it allows me to skip umap but the template code for filtering and debugging the analysis doesn't show up in analyze.49. Is there another way of getting these template code from the jupyter notebook?

**Comment by zhonge** [comment]
The jupyter notebooks should show up regardless of zdim and `--skip-umap`. Can you try deleting the analyze.49 directory and rerunning just to make sure. And if it still doesn't work, can you provide the full log of the command you used and the output from `cryodrgn analyze`? Thanks!

**Comment by EB-kim** [comment]
I have erased the analyze.49 director and rerun the command and this is the output that I am getting.

command input: C:\Users\User\anaconda3\envs\cryodrgn>cryodrgn analyze tutorial/00_vae114 49  --skip-umap --flip --Apix 1.1


Output:
 File "C:\Users\User\anaconda3\envs\cryodrgn\Scripts\cryodrgn-script.py", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.3b0', 'console_scripts', 'cryodrgn')())
  File "C:\Users\User\anaconda3\envs\cryodrgn\lib\site-packages\cryodrgn-0.3.3b0-py3.8.egg\cryodrgn\__main__.py", line 52, in main
    args.func(args)
  File "C:\Users\User\anaconda3\envs\cryodrgn\lib\site-packages\cryodrgn-0.3.3b0-py3.8.egg\cryodrgn\commands\analyze.py", line 198, in main
    subprocess.check_call(cmd, shell=True)
  File "C:\Users\User\anaconda3\envs\cryodrgn\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp C:\Users\User\anaconda3\envs\cryodrgn\lib\site-packages\cryodrgn-0.3.3b0-py3.8.egg\cryodrgn/templates/cryoDRGN_viz_template.ipynb C:\Users\User\anaconda3\envs\cryodrgn\tutorial\00_vae114/analyze.49/cryoDRGN_viz.ipynb' returned non-zero exit status 1.

**Comment by zhonge** [comment]
You're running on windows? Interesting... I changed the cp to be platform-agnostic in 7d0acc02b43663670bb04f262d4e78a951e5a40f. I can't test that it works -- let me know if there are any issues.

**Comment by EB-kim** [comment]
Thank you. I thought it might work since CryoDRGN is running on the anaconda environment, but thank you for the help.

**Comment by EB-kim** [comment]
It works. Thank you.
