### ISSUE TITLE
Handling of CTF and Pose during CryoDRGN setup

### ISSUE THREAD

**Issue by ts387** [zhonge/cryodrgn#65]
Hi:

I am extracting particles which ought to be phase-flipped (using run_data.star from RELION Refine3D, which links to the *shiny.mrcs particle image files in Polish/Micrographs...). Plus the particle contrast therein is white.

But if I backproject these in cryodrgn (i.e. without the --ctf option), I get reversed contrast in the resulting volume (that I can fix using --uninvert-data). However, should I include --ctf (i.e. with the same particles), I do get the right contrast (though as expected the two appear somewhat different).

Does cryoDRGN expect uninverted contrast (black particles), unless the --ctf option is specified? I realise using --ctf with pre-flipped particles could responsible – but kindly let me know.

Also is the expectation for particles to NOT have in-plane shifts and rotations from the consensus reconstruction applied?

I would greatly appreciate any clarification on the matter - many thanks!

**Comment by ts387** [comment]
> Hi:
> 
> I am extracting particles which ought to be phase-flipped (using run_data.star from RELION Refine3D, which links to the *shiny.mrcs particle image files in Polish/Micrographs...). Plus the particle contrast therein is white.
> 
> But if I backproject these in cryodrgn (i.e. without the --ctf option), I get reversed contrast in the resulting volume (that I can fix using --uninvert-data). However, should I include --ctf (i.e. with the same particles), I do get the right contrast (though as expected the two appear somewhat different).
> 
> Does cryoDRGN expect uninverted contrast (black particles), unless the --ctf option is specified? I realise using --ctf with pre-flipped particles could responsible – but kindly let me know.
> 
> Also is the expectation for particles to NOT have in-plane shifts and rotations from the consensus reconstruction applied?
> 
> I would greatly appreciate any clarification on the matter - many thanks!

Addendum: I am advised by Takanori from the RELION team that the above .mrcs are NOT in fact phase-flipped themselves. Only motion-correction ever gets applied to the particle images, while still retaining the original in-plane shifts and rotations within the box (all such parameters are applied on-the-fly during reconstruction using the .star file contents). Is this indeed how cryoDRGN expects a particle images stack?

That would mean I am getting the expected result with the --ctf option specified (but inverted contrast without, using the same particles).

Let me know if there's an explanation I am missing, but feel free to close the issue.

**Comment by Guillawme** [comment]
> Is this indeed how cryoDRGN expects a particle images stack?

I believe yes, because I got meaningful results out of cryoDRGN runs using a star file and an mrcs stack straight from RELION. The maps from cryoDRGN then showed my particle correctly centered in the middle of the box.

I used `relion_stack_create` to generate the particle stack and its corresponding star file, and I haven't checked how this star file compares to the original ones in the RELION jobs, so it's possible that `relion_stack_create` applies the rotation and shifts to ensure the exported particles are centered in the box.

**Comment by ts387** [comment]
Thanks for your answer Guillaume.

I have been assured that RELION doesn't apply in-plane rotations to any `.mrcs` stacks it generates (to avoid interpolation errors). One may choose to apply (only) the integer part of the shifts if you manually enable recentering when reextracting particles – but this isn't the default.

`relion_stack_create` appears to have options to do both, but these aren't the defaults either. 

I used `cryodrgn downsample` to create particle image stacks, i.e. from the RELION `run_data.star` file at the end of 3DRefine – which also contains per-particle orientation, translation and CTF parameters as pertaining to this consensus reconstruction. As we're interested specifically in the conformational heterogeneity of a single refined 3D class, this seems to be appropriate. For full-sized particles, when it comes to the `-D` argument – I simply specify the original box dimension.

It is apparent to me that cryoDRGN parses translations as well as part of `cryodrgn parse_pose_star`, which is how it would get the translation parameters in the Jupyter notebook for example. Hence, I reckon cryoDRG basically handles all the above parameters internally, even as the particle images are not phase-flipped, re-centred or rotated. I don't get any issues with generated volumes which would indicate otherwise either.

I will be looking forward to seeing your results 🙂!

**Comment by Guillawme** [comment]
> I will be looking forward to seeing your results 🙂!

The preprint is now out: https://doi.org/10.1101/2021.06.18.448936
However, I can only release the maps once the peer-reviewed paper is out, so you'll have to wait a bit if you want to take a look at them.

Regarding using particles directly from the relion project or from an export done with `relion_stack_create`, I chose to do the latter because particles within a relion project are always spread across several mrcs files (one per original micrograph), while the cryoDRGN documentation always mentioned a single mrcs file as input. So, I figured this was the only way to make it work, but it looks like it works either way.

**Comment by zhonge** [comment]
Looks like these questions were answered so I am closing this issue (thanks @Guillawme!). 

As a side note, you should be able to use the particles directly from the relion project by providing a `.star` file as the input particles and specifying the directory where all the `.mrcs` files are location with `--datadir` argument.
