### ISSUE TITLE
Missing micrograph coordinate fields in filtered .star files for reextracting particles

### ISSUE THREAD

**Issue by zhonge** [zhonge/cryodrgn#68]
Currently, starfiles converted from cryoDRGN using `write_starfile.py` do not include micrograph information (e.g. rlnCoordinateX, rlnCoordinateY, rlnMicrographName), which are extra fields that we throw out in `cryodrgn parse_ctf_*. However, this info is needed when reextracting at higher/full resolution for refinement back in cryoSPARC/RELION. 

It should be simple to port over the information from the original .cs/.star file in `write_starfile.py`.

**Comment by zhonge** [comment]
Added in commit `8bd8633374709f01b52719f527c4a2f1fd438e9a`. 

A few additional notes:
* Right now only supports .star files and not .cs files since I don't want to get into conversion conventions between cryoSPARC and RELION. 

* Just does the simple thing of copying over the paths to the micrographs given in the reference star file (which may be relative paths). I could add extra logic to convert to absolute paths, but might be unnecessarily complex / user could just make sure the .star file is in the right location when importing back into cryoSPARC/RELION. 

* Logic on filtering could be improved, but this is also hairy. For now, just assert that reference star file corresponds to the the input particles (equal # particles), and filtering them both if `--ind` is provided.

**Comment by Guillawme** [comment]
> * Right now only supports .star files and not .cs files since I don't want to get into conversion conventions between cryoSPARC and RELION.

The [`eulerangles`](https://github.com/alisterburt/eulerangles/) library seems like it could help with this, if you want to provide this feature for particle sets from cryoSPARC.

**Comment by zhonge** [comment]
`write_starfile.py` as of cryodrgn v0.3.4 supports copying over micrograph coordinates and any other specified columns from a reference star file.
