### ISSUE TITLE
How can I reproduce the experiments in the paper? (5.2 and 5.3)

### ISSUE THREAD

**Issue by jaejun-yoo** [zhonge/cryodrgn#8]
Hello. Nice work!
I was impressed by your work and wanted to understand the model by trying the codes and reproducing the experiments in the paper. However, I found it is not quite obvious how I can reproduce the results in the paper. 
For example, I am not sure which main file is corresponding to which experiment. I guess 5.2 HETEROGENEOUS RECONSTRUCTION WITH POSE SUPERVISION can be done by using train_vae.py, but this is also not clear to me from where I have to start. 
It seems like (as far as I understood), the code for 5.3 unsupervised heterogeneous reconstruction is not uploaded yet. 
Would it be possible to have some kinds of step-by-step instructions to get and load data, train the model, and visualize the results?

**Comment by zhonge** [comment]
Thank you Jaejun! You're correct the codebase has moved on quite a bit from the experiments performed in the ICLR paper, mainly to be more user-friendly for application users. If you're interested in reproducing the experiments, send me an email (zhonge@mit.edu), and we can figure out how to transfer the datasets.

**Comment by Icecream-blue-sky** [comment]
> Hello. Nice work!
> I was impressed by your work and wanted to understand the model by trying the codes and reproducing the experiments in the paper. However, I found it is not quite obvious how I can reproduce the results in the paper.
> For example, I am not sure which main file is corresponding to which experiment. I guess 5.2 HETEROGENEOUS RECONSTRUCTION WITH POSE SUPERVISION can be done by using train_vae.py, but this is also not clear to me from where I have to start.
> It seems like (as far as I understood), the code for 5.3 unsupervised heterogeneous reconstruction is not uploaded yet.
> Would it be possible to have some kinds of step-by-step instructions to get and load data, train the model, and visualize the results?

Hi，have you got the code from the author? I also want to reproduce this paper and find the same problem as you. Could you send me a copy of  the code to my email(tqzouustc@mail.ustc.edu.cn ) if you have got it?  Thank you very much!!
