### ISSUE TITLE
trying to convert back to .star file

### ISSUE THREAD

**Issue by am2837** [zhonge/cryodrgn#82]
Hi!
im trying to convert a subset of particles back to a star file. Im following the tutorial commands however I am still getting an error. 
$ python $SRC/utils/write_starfile.py 128/particles.128.mrcs ctf.pkl --poses poses.pkl --ind training/ind_keep.458052_particles.pkl --full-path -o test.star
  File "/programs/x86_64-linux/cryodrgn/0.3.2/utils/write_starfile.py", line 49
    assert len(particles) == len(ctf), f"{len(particles)} != {len(ctf)}, Number of particles != number of CTF paraameters"
                                                                                                                         ^
SyntaxError: invalid syntax

Thanks!
Arnold

**Comment by zhonge** [comment]
Hi Arnold, it does look like there's a python version issue since there shouldn't be a syntax error with python 3.x in that line. Agreed with what @kttn8769 commented!
