### ISSUE TITLE
GeForce RTX 3090 not compatible with  PyTorch

### ISSUE THREAD

**Issue by Adrian-Plaza** [zhonge/cryodrgn#91]
Hi, I am trying to run cryodrgn to train a model with the following command:

cryodrgn train_vae particles.128.mrcs --poses pose.pkl --ctf ctf.pkl --zdim 8 -n 50 -o 00_vae128_z8_n50

but I got the following error:
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.

I installed PyTorch 1.18 and then tried with PyTorch 1.17 but got the same error.
The CUDA Version is 11.2.

Do you have sny insight regarding this error?
Thank you
Adrian

**Comment by zhonge** [comment]
It looks like it is an incompatibility between your pytorch and CUDA versions. How did you install pytorch? I would try searching the pytorch discussion pages to see if there's anything helpful there, e.g. https://discuss.pytorch.org/t/geforce-rtx-3090-with-cuda-capability-sm-86-is-not-compatible-with-the-current-pytorch-installation/123499/9/
