### ISSUE TITLE
Will cryoDRGN2 be open-source or be updated here?

### ISSUE THREAD

**Issue by ChierCS** [zhonge/cryodrgn#95]
Hi, Ellen zhong. I'm very interested in this good job. And I read the ICCV2021 paper cryoDRGN2. Will it be open-source?  Or it will be found in this project soon?

**Comment by zhonge** [comment]
It will be open-sourced soon! Shoot me an email (zhonge@mit.edu) if you would like to try it out before public release.

**Comment by zhonge** [comment]
To the people that emailed me about this, I will get back to you after the new year :)
