### ISSUE TITLE
cryodrgn analyze yielded inverted map

### ISSUE THREAD

**Issue by sunchang1990** [zhonge/cryodrgn#97]
The cryodrgn installed is ver 7a79f1cc8e62e26df9bdf2d30d068a6ad474b901

I followed the EMPIAR-10076 tutorial on Notion. One slight change is to downsample particle images to 120x120 rather than 128x128. The 50-iteration cryodrgn training finished as expected, with roughly the same execution time and UMAP clusters as documented. 

The analysis was produced by the following command (Note the pixel size was changed to account for the different downsamplings):
cryodrgn analyze 00_vae120 49 --flip --Apix 3.493

However, all the produced maps were inverted and looked strange in chimera. After being inverted with relion_image_handler, the produced maps made sense and did represent the structural heterogeneity quite nicely.

I had then tried to re-analyze with the --invert option, but the produced maps were still inverted. Thus, it appears there is a bug with the cryodrgn analyze script.

**Comment by zhonge** [comment]
Thanks for reporting! It should be fixed in 6282fa94657438df692c3e309a88b8e258d17fa2.
